blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - tables_setup
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: load_local_files
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: load_local_files
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - inject_to_sqlite
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: Tables_setup
  retry_config: null
  status: executed
  timeout: null
  type: transformer
  upstream_blocks:
  - load_local_files
  uuid: tables_setup
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: inject_to_sqlite
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - tables_setup
  uuid: inject_to_sqlite
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2025-06-18 14:29:26.033878+00:00'
data_integration: null
description: charge les fichier CSV locaux dans la bdd sqlite
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: init_db
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: init_db
variables_dir: /root/.mage_data/app
widgets: []
