blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - define_views
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: Create_views
  retry_config: null
  status: failed
  timeout: null
  type: data_exporter
  upstream_blocks: []
  uuid: create_views
- all_upstream_blocks_executed: false
  color: teal
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: define_views
  retry_config: null
  status: executed
  timeout: null
  type: custom
  upstream_blocks:
  - create_views
  uuid: define_views
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2025-06-23 14:37:01.887795+00:00'
data_integration: null
description: Creation de vues sur les différents indicateurs de performance
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: create_views
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: create_views
variables_dir: /root/.mage_data/app
widgets: []
